### PR TITLE
refactored a function according to patch provided

### PR DESCRIPTION
**Pull request by sfranky**

### CODE REVIEW

**Comment by fgeorgatos** [comment]
does this fix a bug? if so, which? what about tests?

**Comment by sfranky** [comment]
Quoting @lookfwd

> I think this was a bit complex and unnecessarily of N^2 complexity. The name was also a bit deceptive since it wasn't really a "get" and it modifies the argument.

**Comment by sfranky** [comment]
all tests pass.

**Comment by fgeorgatos** [comment]
merged

**Pull request merged**
