### PR TITLE
changed README.rst to README.md

### PR DESCRIPTION
**Pull request by raiiden15**

### CODE REVIEW

**Review by archita-2810 — APPROVED** [review]
changes are correct

**Comment by fgeorgatos** [comment]
thanks @raiiden15, this LGTM!

This is a hotfix under this gitflow regime: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
From this point on, I will recreate `develop` branch so that most activity happens there between releases!

**Comment by fgeorgatos** [comment]
@raiiden15 welcome to qtop!

Let us know if merging the PR is sufficient for your hacktoberfest credits (I think it is) and you feel touching another issue.

**Comment by fgeorgatos** [comment]
fixes #326

**Pull request merged**
